version: '3'
volumes:
  dados:
services:
  cache:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - D:/Docker/Volume/data:/var/opt/mssql/data
      - D:/Docker/Volume/log:/var/opt/mssql/log
      - D:/Docker/Volume/secrets:/var/opt/mssql/secrets
  cadastro:
    build: Cadastro/Cadastro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dockerapi
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/.aspnet/https:/https:ro